
# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Swift.gitlab-ci.yml

# Lifted from: https://about.gitlab.com/2016/03/10/setting-up-gitlab-ci-for-ios-projects/
# This file assumes an own GitLab CI runner, setup on a macOS system.
stages:
  - build
  - test

build_project:
  stage: build
  script:
    - xcodebuild clean -project Calculator-iOS.xcodeproj -scheme Calculator-iOS | xcpretty
    - xcodebuild test -project Calculator-iOS.xcodeproj -scheme Calculator-iOS -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.4' | xcpretty -s
  tags:
    - ios

unit_tests
  stage: test
  script:
    - xcodebuild -scheme Calculator-iOS -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.4' test | xcpretty color
  tags:
    - ios
    

archive_project:
  stage: archive
  script:
    - xcodebuild clean archive -archivePath build/Calculator-iOS -scheme Calculator-iOS
    - xcodebuild -exportArchive -exportFormat ipa -archivePath "build/Calculator-iOS.xcarchive" -exportPath "build/Calculator-iOS.ipa" -exportProvisioningProfile "ProvisioningProfileName"
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  artifacts:
    paths:
      - build/Calculator-iOS.ipa
  tags:
    - ios
